### ISSUE TITLE
Sharing buttons desappearing

### ISSUE THREAD

**Issue by MikeBinstock** [h4t0n/odin#2]
In your demo, sharing buttons are appearing, and then dissapearing.
Tested on latest Google Chrome version 49.

**Comment by h4t0n** [comment]
Probably due to a [RRSSB](https://github.com/kni-labs/rrssb) bug. I have Chrome 47 and latest Chromium/Canary 50 (OSX OS) and I don't see any issue. What's your operating system ? Could you be more specific?

**Comment by MikeBinstock** [comment]
Yes, I've verified and the problem is uBlock. It is blocking RRSSB. I don't know why, it's important because uBlock is well known.

**Comment by h4t0n** [comment]
Ok, so once RRSSB fix it I'll update the dependency.

**Comment by MikeBinstock** [comment]
Tks! I've opened an issue in RRSSB.

**Comment by h4t0n** [comment]
kni-labs/rrssb#164
