### ISSUE TITLE
Font issue: Letter f not displaying for some reason.

### ISSUE THREAD

**Issue by thebugcode** [h4t0n/odin#3]
Hi, Its wierd, but it looks like when you use this theme and use words like
"find" or "file" the letter f doesnt get displayed.  You can search for "find" in this post and see the issue:
https://blog.h4t0n.com/nodejs-rest-api/

Any ideas?

**Comment by h4t0n** [comment]
This issue is not related to the Odin theme. It's a Google Fonts bug. It should be fixed soon. Some info here TryGhost/Casper#235

**Comment by h4t0n** [comment]
Google fixed it.
