### ISSUE TITLE
No Syntax Highlighting

### ISSUE THREAD

**Issue by jswny** [h4t0n/odin#4]
It seems like the syntax highlighting in Odin is not working. I've included screenshots of my blog with the regular code blocks. The code blocks are missing the dark background as well as the syntax highlighting.
<img width="906" alt="screen shot 2016-03-31 at 11 12 50 pm" src="https://cloud.githubusercontent.com/assets/3282078/14196845/3955d7e2-f796-11e5-8401-3e811bde1d0d.png">
<img width="1108" alt="screen shot 2016-03-31 at 11 12 59 pm" src="https://cloud.githubusercontent.com/assets/3282078/14196846/395ffe84-f796-11e5-950f-2afcb5641f2f.png">

**Comment by Penguin4eg** [comment]
Try use 
`
```language-javascript
Your code
```
`

**Comment by Penguin4eg** [comment]
Try to use
```language-javascript
Your code
```

**Comment by lissergey** [comment]
Try use 
<img width="232" alt="2016-04-01 21 24 35" src="https://cloud.githubusercontent.com/assets/14940294/14216182/2a759edc-f850-11e5-83fe-6592aa6d3ddf.png">

**Comment by h4t0n** [comment]
@Penguin4eg is right...
