### ISSUE TITLE
Social links not working with mailto:

### ISSUE THREAD

**Issue by bravoborja** [h4t0n/odin#5]
If I add a new icon for social_links not working with mailto. Example in ghost_head:
var social_link = {
    'github-square': 'https://github.com/bravoborja',
    'envelope' : 'mailto:example@mail.com'
}

I create new icon(envelope in css) but not displayed. 
If I changed envelope by other url, then, it is worked.

**Comment by bravoborja** [comment]
I close this issue. You consider only url regex. I'll work my custom version, thanks

**Comment by h4t0n** [comment]
You can send me a Pull Request to support also the mailto if you want. In my blog I use the menu for this purpose.
