### ISSUE TITLE
How to disable some social media buttons?

### ISSUE THREAD

**Issue by ric2b** [h4t0n/odin#6]
Hi!
Thanks for the awesome theme, btw.
I just don't know how to disable the social media buttons, is there some code injection I can do?

Thanks!

**Comment by h4t0n** [comment]
Social Media are disabled by default. Check if you have the **social_link** variable in your Header Code Injection and remove it (or set to false).

**Comment by ric2b** [comment]
I have the social_link variable commented out in my Header Code but the social media buttons still show up. Ideally I'd like to disable just the ones at the top of the post and leave the ones at the bottom (except maybe remove ones for sites I don't find relevant).
My Header Code Injection looks like this:

```
// to enable Google Analytics
var ga_id = 'UA-86857844-1';

// to enable Disqus
var disqus_shortname = 'devbrainblog';


// to enable Social Link Icons add the social_link object
// with the pair key/value -> social_network/link
// NB: the key is used to include the right icon from Font Awesome
// (you can include any Font Awesome icon)

// Example1: default social network icons
/*var social_link = {
    'twitter': 'https://twitter.com/h4t0n',
    'linkedin': 'https://it.linkedin.com/in/andreatarquini',
    'github': 'https://github.com/h4t0n',
    'rss':'https://blog.h4t0n.com/rss/'
    // you can add more icons
}*/

// Example2: squared social network icons
/*var social_link = {
    'twitter-square': 'https://twitter.com/h4t0n',
    'linkedin-square': 'https://it.linkedin.com/in/andreatarquini',
    'github-square': 'https://github.com/h4t0n',
    'rss':'https://blog.h4t0n.com/rss/'
    // you can add more icons
}*/
```

Every single social media button still shows up: http://cat.devbra.in/pair-a-bluetooth-le-device-with-a-dualboot-of-linux-windows-10/

**Comment by h4t0n** [comment]
Ohh ok, you are talking about RRSSB Social Sharing Buttons. They cannot be disabled by code injection. You can remove any section `<section class="social-share">` of  **post.hbs**.

**Comment by ric2b** [comment]
Ah, thank you!
I was able to remove the buttons at the top as I wanted.
Is there a way to remove just a few of the ones at the bottom as well?

**Comment by h4t0n** [comment]
Sure, you can remove the social share link you want from _partials/social_share.hbs_

**Comment by ric2b** [comment]
Thank you! :D
